CREATE OR REPLACE PROCEDURE updatecrypto (name varchar, currency varchar, price decimal, highday decimal, lowday decimal, changepct24h decimal, lastupdate varchar)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE
        cryptos
    SET
        cryptos.name = name,
        currency = currency,
        price = price,
        highday = highday,
        lowday = lowday,
        changepct24h = changepct24h,
        lastupdate = lastupdate;
    COMMIT;
END;
$$;

